# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-03 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entities', models.TextField(default='[]')),
                ('relations', models.TextField(default='[]')),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textname', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='progress',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZA.Text'),
        ),
        migrations.AddField(
            model_name='progress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ZA.User'),
        ),
    ]
