# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZA', '0002_auto_20170804_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app',
            field=models.CharField(default='ZA', max_length=20),
        ),
    ]
